config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  devise_for :users, controllers: { registrations: 'registrations' }, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }
  devise_scope :users do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy"
  end

  get 'users/show'
  resources :rooms do
    collection do
      get :search
    end
  end
  resources :reservations do
    collection do
     get :complete# 完了画面
    end
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
	belongs_to :room
	belongs_to :user


	validates :check_in, presence: true
	validates :check_out, presence: true
	validates :customer, numericality: true

	def amount_days
		self.total_days = (self.check_out - self.check_in).to_i
	end
	def amount_price
		self.total_amount = self.room.price.to_i * self.customer.to_i * amount_days
	end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_current_user
  before_action :authenticate_user!
  def index
    #予約済みの部屋を表示
    @user = current_user
    @reservations = Reservation.all.page(params[:page]).per(5)
  end
  def new
    @user = current_user
    @reservation = Reservation.new(reservation_params)
    @reservation.user_id = current_user.id

    if @reservation.check_in.nil? || @reservation.check_out.nil?
      redirect_to @reservation.room, notice: "日付を指定してください。"
    elsif @reservation.check_out < Date.today || @reservation.check_in < Date.today
      redirect_to @reservation.room, notice: "今日より過去の日付は指定できません。"
    elsif @reservation.check_out == @reservation.check_in
      redirect_to @reservation.room, notice: "同じ日付は指定できません。"
    elsif @reservation.check_out < @reservation.check_in
      redirect_to @reservation.room, notice: "チェックインより後の日付を指定してください。"
    elsif @reservation.customer == nil
      redirect_to @reservation.room, notice: "人数を指定してください。"
    else
    @reservation.total_days = @reservation.amount_days.to_i
    @reservation.total_amount = @reservation.amount_price.to_i
    @reservation.save
    end
  end

  def create
    #入力画面
    @reservation = Reservation.new(reservation_params)
    @reservation.user_id = current_user.id
    @room = Room.find(params[:id])
    @reservation.room_id = @room.id
  end


  def complete
    @user = current_user
    @reservation = Reservation.new(reservation_params)


  end


  def edit
  end

  def update

  end

  def destroy
  end

  private
    def reservation_params
      params.require(:reservation).permit(:user_id, :check_in, :check_out, :customer, :room_id, :total_days, :total_amount)
    end



end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/complete.html.erb
<h2>
 <span class="caption_complete_reserve">予約完了</span>
</h2>

<div class="complete_reserve_detail">

  <table class="complete_detail">
    <tr>
	    <th>予約した部屋</th>
      <td><%= @reservation.room.name %></td>
    </tr>
      <th>チェックイン</th>
      <td><%= @reservation.check_in %></td>
    </tr>
    <tr>
	    <th>チェックアウト</th>
      <td><%= @reservation.check_out %></td>
    </tr>
    <tr id="complete_amount">
	    <th>合計金額</th>
      <td>¥ <%= @reservation.total_amount %></td>
    </tr>
  </table>
  <div class="return_top_btn">
  <%= link_to "トップページに戻る", "/", class:"return_top" %>
  </div>
</div>

app/views/reservations/index.html.erb
<h2>
 <span class="caption_index_reserv">
  <%= link_to "予約したルーム一覧", :reservations ,id:"new_rooms" %>
 </span>
</h2>

<div class="box_index_reserv">

 <% if flash[:notice] %>
  <div class="flash">
	<%= flash[:notice] %>
  </div>
 <% end %>

 <table class="index_reserv">
  <div class="page" >
   <%= paginate @reservations %>
  </div>
  <thead>
    <tr>
	  <th>ルーム画像</th>
	  <th>ルーム名</th>
	  <th>ルーム紹介</th>
	  <th>料金</th>
	  <th>チェックイン</th>
	  <th>チェックアウト</th>
	  <th>予約確定日</th>
	</tr>
  </thead>

  <tbody>
	<% @reservations.each do |reserve| %>
	 <% if reserve.user_id == current_user.id %>
	 <tr>
	  <% if reserve.room.image.present? %>
	   <td><%= link_to image_tag(reserve.room.image.variant(resize:'250x250'), clss: "rooms_icon"), room_path(id: reserve.room_id) %></td>
	  <% end %>
	  <td><%= link_to reserve.room.name,room_path(id: reserve.room_id) ,class:"name_link" %></td>
	  <td><%= reserve.room.introduction %></td>
	  <td>¥ <%= reserve.room.price %></td>
	  <td><%= reserve.check_in.strftime("%Y年%m月%d日") %></td>
	  <td><%= reserve.check_out.strftime("%Y年%m月%d日") %></td>
	  <td><%= reserve.updated_at.to_s(:datetime_jp) %></td>
	 </tr>
	 <% end %>
	<% end %>
  </tbody>
 </table>
</div>

app/views/reservations/new.html.erb
<h2>
 <span class="caption_new_reserve">予約内容確認</span>
</h2>

<div class="new_reserve_box">
  <div class="new_reserve_detail">

   <div class="room_reserve">
    <%= "ルーム名: #{@reservation.room.name}" %>
    <span class="space">
      <%= "¥ #{@reservation.room.price} / 日" %>
    </span>
   </div><br>

    <p class="reserve_detail">チェックイン</p>
    <span class="check"><%= @reservation.check_in %></span>

    <p class="reserve_detail">チェックアウト</p>
    <span class="check"><%= @reservation.check_out %></span><br>

   <div class="room_reserve">
    <%= "使用日数:  #{@reservation.total_days}日" %>
   </div><br>

   <div class="room_reserve">
    <%= "人数: #{@reservation.customer}人" %>
   </div><br>

   <div class="room_reserve">
    <%= "合計金額: ¥ #{@reservation.total_amount}" %>
   </div>

    <p id="make_sure">上記内容でよろしければ「予約を確定」を押してください。<p>
  </div>

  <%= form_with model: @reservation, method: :get, url: complete_reservations_path do |r| %>
    <%= r.hidden_field :check_in ,value:@reservation.check_in %>
    <%= r.hidden_field :check_out,value:@reservation.check_out  %>
    <%= r.hidden_field :customer,value:@reservation.customer %>
	  <%= r.hidden_field :room_id ,value: @reservation.room_id%>
	  <%= r.hidden_field :user_id,value: current_user.id  %>
	  <%= r.hidden_field :total_days,value:@reservation.total_days %>
	  <%= r.hidden_field :total_amount,value:@reservation.total_amount %>

    <ul class="reserve_choose">
      <li id="submit_new_reserve_border"><%= r.submit "予約を確定する",id:"submit_new_reserve" %></li>
		  <li id="return_reserve_bottom"><%= link_to "予約画面に戻る", :rooms ,id:"return_reserve" %></li>
    </ul>

  <% end %>
</div>