config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  devise_for :users, controllers: { registrations: 'registrations' }, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }
  devise_scope :users do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy"
  end

  get 'users/show'
  resources :rooms do
    collection do
      get :search
    end
  end
  resources :reservations do
    collection do
     get :complete# 完了画面
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord
	has_many :reservations,dependent: :destroy
	belongs_to :user

	validates :name, presence: true
	validates :introduction, presence: true
	validates :introduction, length: {maximum: 30}
	validates :price, numericality: true
	validates :address, presence: true
	validates :image, presence: true

	has_one_attached :image

	def self.search(search)
		if search
			Room.where(['name LIKE ? OR address LIKE ? OR introduction LIKE ? ', "%#{search}%", "%#{search}%", "%#{search}%"])
		else
		  Room.all
		end
	end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!, except: [:search]
  def index
    @rooms = Room.all.page(params[:page]).per(5)
    @user = current_user
  end
  def new
    @user = current_user
    @room = Room.new
  end
  def create
    @room = Room.new(params.require(:room).permit(:name,:introduction,:address,:price,:image))
    @room.user_id = current_user.id
    @user = current_user
    if @room.save
      redirect_to :rooms
      flash[:notice] = "部屋の登録が完了しました"
    else
      render "new"
    end
  end

  def search
    @user = current_user
    @rooms = Room.search(params[:search])

  end

  def show
#自分が登録したルームを表示させる
   @user = current_user
   @room = Room.find(params[:id])
   @room.user_id = current_user.id
   @reservation = Reservation.new
   @reservation.room_id = @room.id

  end

  def edit
  end

  def update
  end

  def destroy

  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/index.html.erb
<h2>
 <span class="caption_index_room">
 <%= link_to "登録したルーム一覧", :rooms ,id:"new_rooms"%>
 </span>
</h2>

<div class="box_index_room">

 <% if flash[:notice] %>
  <div class="flash">
	<%= flash[:notice] %>
  </div>
 <% end %>

 <table class="index_room">
  <div class="page">
   <%= paginate @rooms %>
  </div>

   <thead>
    <tr>
	  <th>ルーム画像</th>
	  <th>ルーム名</th>
	  <th>ルーム紹介</th>
	  <th>料金</th>
	  <th>作成日</th>
	</tr>
   </thead>
   <tbody>
	<% @rooms.each do |room| %>
	 <% if room.user_id == current_user.id %>
	  <tr>
	   <% if room.image.present? %>
	  	<td><%= link_to image_tag(room.image.variant(resize:'250x250'),clss: "rooms_icon" ),room %></td>
	   <% end %>
	  	<td><%= link_to room.name , room,class:"name_link" %></td>
	  	<td><%= room.introduction %></td>
	  	<td>¥ <%= room.price %></td>
		<td><%= room.updated_at.to_s(:datetime_jp) %></td>
	 </tr>
	 <% end %>
	<% end %>
   </tbody>
 </table>
</div>

app/views/rooms/new.html.erb
<h2>
 <span class="caption">
  <%= link_to "ルーム情報登録", :new_room ,id:"new_rooms" %>
 </span>
</2>
<div class="box">
 <%= render"shared/error", obj: @room %>
  <%= form_with model: @room do |f| %>
   <table class="room-register">

    <tr>
      <th><%= f.label :name ,"ルーム名" %><p class="require">必須</p></th>
      <td><%= f.text_field :name ,placeholder:"ルーム名" %></td>
    </tr>
    <tr>
      <th><%= f.label :introduction ,"ルーム紹介" %><p class="require">必須</p></th>
      <td><%= f.text_area :introduction,placeholder:"ルーム紹介" %></td>
    </tr>
    <tr>
      <th><%= f.label :price ,"料金" %><p class="require">必須</p></th>
      <td><%= f.number_field :price,placeholder:"1日の料金 *数字で入力" %></td>
    </tr>
		<tr>
      <th><%= f.label :address ,"住所" %><p class="require">必須</p></th>
      <td><%= f.text_field :address,placeholder:"アドレス" %></td>
    </tr>
    <tr>
      <th><%= f.label :image ,"ルーム画像"%><p class="require">必須</p></th>
      <td><%= f.file_field :image %></td>
    </tr>
   </table>


    <ul class="room-submit">
      <li><%= f.submit "登録" , id:"submit-btn" %></li>
		  <li ><%= link_to "部屋一覧に戻る", :rooms ,id:"room-return" %></li>
    </ul>
  <% end %>
</div>

app/views/rooms/search.html.erb
<div class="search_page">
<h2 class="count_result">検索結果 :<span>
   <%= Room.where('name LIKE ? OR address LIKE ? OR introduction LIKE ?',"%#{params[:search]}%","%#{params[:search]}%","%#{params[:search]}%").count %>
</span>件</h2>

<div class="result">
  <% @rooms.each do |room| %>
  <ul class="result_display" >
    <% if room.image.present? %>
     <li><%= link_to image_tag(room.image.variant(resize:'320x320')),room, clss: "search_rooms" %></li>
    <% end %>
    <li id="search_name"><p><%= room.name%></p></li>
    <li id="search_address"><p><%= room.address %></p></li>
    <li id="search_price"><p>¥<%= room.price %></p></li>
   </ul>
  <% end %>
</div>
</div>

app/views/rooms/show.html.erb
<div class="show_room_reserve">
  <div class="room_show">
    <% if @room.user_id == current_user.id %>
    <% if @room.image.present? %>
      <%= image_tag @room.image.variant(resize:'800x500'), clss: "room_image"  %><br>
     <div class="room_photo_intro">
      <%= link_to image_tag(@room.user.image.variant(resize:'70x70')),users_show_path, clss: "user_photo" %>
    <% end %>
     <div class="room_intro">
     <ul>
	    <li id="room_names"><%= @room.name %></li>
      <li><%= @room.address %></li>
     </ul>
     </div>
     </div>
     <p class="room-information"><%= @room.introduction %></p>
   <% end %>
  </div>

 <div class="show_reserve">
  <div class="reservation_error">
    <%= render"shared/error", obj: @reservation %>
	  <%= notice %>
  </div>
  <%= form_with model: @reservation, url: new_reservation_path, method: :get ,local: true do |r| %>
    <p><%= "¥#{@room.price} / 日" %></p><br>

    <%= r.label :check_in ,"チェックイン" %><br>
    <%= r.date_field :check_in ,class:"reservation_day" %><br>
    <%= r.label :check_out ,"チェックアウト" %><br>
    <%= r.date_field :check_out ,class:"reservation_day" %><br>
  	<%= r.label :customer,"人数" %><br>
    <%= r.number_field :customer, min: 1 ,class:"reservation_num" %><br>
		<%= r.hidden_field :room_id, value: @room.id %>
		<%= r.hidden_field :user_id, value: current_user.id %>
  <div class="show_reserve_btns">
    <ul >
      <li><%= r.submit "予約を確認する",id:"if_reserve_btn" %></li>
		  <li id="return_room_index_btn"><%= link_to "戻る", :rooms,id:"return_room_index" %></li>
    </ul>
  </div>
  <% end %>
</div>